'use strict';

// Entirely synthetic, in-memory scenario. No API, model calls, tracking, or storage.
const $ = (selector) => document.querySelector(selector);
const state = { started: false, changed: false, impactSeen: false, reviewed: false, finished: false, attempted: false, panel: 'contract', packets: [], selectedPacket: null };
const contract = {
  1: { title: 'Usage amounts travel as integer cents', body: '{\n  amount_cents: 1234,\n  currency: "USD"\n}', explanation: 'Divide amount_cents by 100 to display the total. The first contract assumes two decimal places.' },
  2: { title: 'Usage amounts include a currency exponent', body: '{\n  amount_minor: 1234,\n  currency: "BHD",\n  currency_exponent: 3\n}', explanation: 'Support currencies with zero or three decimal places. Read amount_minor and divide by 10 ** currency_exponent.' }
};
const claim = {
  1: 'Display total = amount_cents / 100. Format it using the response currency.',
  2: 'Display total = amount_minor / 10 ** currency_exponent. Format it using the response currency.'
};
const icons = {
  link: '<svg viewBox="0 0 24 24"><path d="m10 13 4-4M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 1 1 6 6l-5 5a4 4 0 0 1-6 0" transform="translate(2 0) scale(.85)"/></svg>',
  branch: '<svg viewBox="0 0 24 24"><circle cx="6" cy="5" r="2.5"/><circle cx="6" cy="19" r="2.5"/><circle cx="18" cy="6" r="2.5"/><path d="M6 8v8m12-7a9 9 0 0 1-9 9"/></svg>',
  check: '<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
  alert: '<svg viewBox="0 0 24 24"><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v4m0 3v1"/></svg>',
  file: '<svg viewBox="0 0 24 24"><path d="M5 3h9l5 5v13H5V3Zm9 0v6h5M8 13h8m-8 4h6"/></svg>',
  arrow: '<svg viewBox="0 0 24 24"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>'
};
const icon = (name) => `<span class="icon" aria-hidden="true">${icons[name]}</span>`;
const escape = (value) => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const button = (label, action, className = 'secondary', disabled = false) => `<button class="button ${className}" data-action="${action}" ${disabled ? 'disabled' : ''}>${label}</button>`;

function createPacket() {
  const version = state.changed ? 2 : 1;
  const claimVersion = state.reviewed ? 2 : 1;
  const manifest = [
    { id: 'api.usage', title: 'Usage API contract', version, mode: 'live' },
    { id: 'ui.display', title: 'Currency display rule', version: claimVersion, mode: 'owned', dependency: claimVersion },
    { id: 'security.tenant', title: 'Tenant identity comes from the session', version: 1, mode: 'live' }
  ];
  const text = `# Loomplane synthetic context packet\nTask: Implement the usage total\nStream: Usage dashboard\n\n## Usage API contract @v${version}\n${contract[version].body}\n${contract[version].explanation}\n\n## Currency display rule @v${claimVersion}\n${claim[claimVersion]}\nDerived from: api.usage@v${claimVersion}\n\n## Tenant boundary @v1\nDerive tenant_id from the authenticated session. Never trust a query parameter.\n\n## Exact revision manifest\n${manifest.map(item => `${item.id}@v${item.version} (${item.mode})`).join('\n')}\n`;
  const packet = { id: `packet-demo-${String(state.packets.length + 1).padStart(2, '0')}`, manifest, text, tokens: Math.ceil(text.length / 4), budget: 1200 };
  state.packets.push(packet);state.selectedPacket = packet.id;return packet;
}
function checkPacket(packet) {
  if (!packet) return [];
  const changes = [];
  const apiEntry = packet.manifest[0], derived = packet.manifest[1];
  if (state.changed && apiEntry.version === 1) changes.push({ type: 'direct', title: 'API contract changed', text: 'This immutable packet used api.usage@v1. The shared source is now v2.' });
  if (state.changed && derived.dependency === 1) changes.push({ type: 'dependency', title: 'Derived claim needs review', text: 'The display rule was based on api.usage@v1. Copying the current API text into a new packet does not validate that rule.' });
  if (state.reviewed && derived.version === 1) changes.push({ type: 'revision', title: 'Display rule changed', text: 'This packet contains ui.display@v1. A reviewed v2 is now available.' });
  return changes;
}
function currentPacket() { return state.packets.find(p => p.id === state.selectedPacket) ?? state.packets.at(-1); }
function showToast(text) { const toast=$('#toast');toast.textContent=text;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,4000); }
function selectedPanel(panel) { state.panel=panel;render(); }
function renderGuide() {
  let step, title, text, action, label;
  if (!state.started) { step=1;title='Give the UI task a precise starting context.';text='Compile contract v1 and the UI display rule into an exact packet. Record a synthetic task against that snapshot.';action='start';label='Record a synthetic task'; }
  else if (!state.changed) {step=2;title='The API agent changes the shared contract.';text='The API must support currencies with three decimal places. Publish v2 while the UI task still holds its v1 packet.';action='change';label='Change API contract';}
  else if (!state.impactSeen) {step=3;title='The old packet is now visibly stale.';text='Trace direct consumers and the QA plan that depends on the UI rule. The original packet stays exactly as it was.';action='impact';label='Inspect the impact';}
  else if (!state.reviewed) {step=4;title=state.attempted?'A new packet can still contain an old assumption.':'Review the claim derived from the old contract.';text=state.attempted?'The recompiled packet includes API v2, but its display rule still depends on v1. Review that rule before claiming the context is current.':'Refreshing source text is only one step. A claim based on the old contract needs an explicit review and a new dependency revision.';action='review';label='Review the display rule';}
  else if (!state.finished) {step=5;title='Now compile the reviewed context.';text='The display rule explicitly references API v2. Compile a new packet and compare it with the original task snapshot.';action='compile-final';label='Compile a fresh packet';}
  else {step=5;title='The dashboard has current context. History is intact.';text='Your new packet passed this synthetic preflight. QA still owns a stale derived plan and needs its own review. No model was run.';action='original';label='Compare original packet';}
  $('#step-number').textContent=String(step).padStart(2,'0');$('#guide-title').textContent=title;$('#guide-text').textContent=text;$('#next-step').textContent=label;$('#next-step').dataset.action=action;
  $('#step-total').textContent=state.finished?'complete':'/ 05';
  $('#board-health').className=state.changed?'board-alert':'board-current';
  $('#board-health').innerHTML=state.changed?`${icon('alert')}${state.finished?'QA still needs review':'2 streams have changed dependencies'}`:`${icon('check')}Sources agree at v1`;
}
function renderBoard() {
  const apiVersion=state.changed?2:1, displayVersion=state.reviewed?2:1, latest=state.packets.at(-1), uiStale=latest && checkPacket(latest).length>0;
  $('#stream-board').innerHTML=`
    <article class="stream-lane purple"><header><div class="lane-identity"><span class="agent-avatar">A</span><div><h3>Billing API</h3><p>API agent · independent stream</p></div></div><span class="branch">${icon('branch')}feat/billing-api</span><div class="lane-status"><span class="status-current">${icon('check')}Source published</span><span>Contract v${apiVersion}</span></div></header><div class="lane-body"><div class="lane-section">Published here</div><button class="capsule-card ${state.panel==='contract'?'selected':''}" data-action="contract"><div class="card-top"><span class="kind">${icon('branch')}Decision</span><span>v${apiVersion}</span></div><h4>${contract[apiVersion].title}</h4><pre>${escape(contract[apiVersion].body)}</pre><div class="card-bottom">${icon('file')}Synthetic contract source<span>api.usage</span></div></button><div class="source-note">${icon('link')}Connected to the dashboard.<br>Changes also reach derived claims.</div>${state.changed?'<div class="publication-note">New revision published.<br>Previous revisions stay immutable.</div>':button('Publish contract v2','change','lane-action',!state.started)}</div><footer><span class="stream-scope">Owns the response contract</span><button class="text-button" data-action="contract">Inspect source ${icon('arrow')}</button></footer></article>
    <article class="stream-lane coral"><header><div class="lane-identity"><span class="agent-avatar">U</span><div><h3>Usage dashboard</h3><p>UI agent · independent stream</p></div></div><span class="branch">${icon('branch')}feat/usage-panel</span><div class="lane-status"><span class="${uiStale?'status-changed':'status-current'}">${icon(uiStale?'alert':'check')}${!state.started?'Ready for context':uiStale?'Packet needs review':'Packet current'}</span><span>Display v${displayVersion}</span></div></header><div class="lane-body">${uiStale?`<div class="drift-alert"><strong>${icon('alert')}${state.attempted&&!state.reviewed?'Recompiled. Still stale.':'Shared context changed'}</strong><p>${state.reviewed?'A reviewed display rule is ready. Compile it into a new packet.':'API v2 changed the assumptions behind this display rule.'}</p><button class="text-button" data-action="impact">Inspect impact ${icon('arrow')}</button></div>`:''}<div class="lane-section">Derived in this stream</div><button class="capsule-card ${state.panel==='review'?'selected':''}" data-action="${state.changed?'review':'display'}"><div class="card-top"><span class="kind">${icon('branch')}Decision</span><span>v${displayVersion}</span></div><h4>Format the usage total</h4><p>${claim[displayVersion]}</p><div class="dependency-chip ${state.changed&&!state.reviewed?'outdated':''}">${icon('link')}Based on API contract v${displayVersion}</div><div class="card-bottom">${icon('file')}Synthetic UI decision<span>ui.display</span></div></button><div class="lane-section connected">${icon('link')}Shared context</div><button class="shared-card" data-action="contract"><span class="shared-dot"></span><span>Usage API contract<small>Following latest source</small></span><span>v${apiVersion}</span></button>${latest?`<button class="packet-card ${uiStale?'stale':''}" data-action="packet">${icon('file')}<span>${latest.id}<small>Exact revisions · ~${latest.tokens} tokens</small></span><span class="packet-indicator">${icon(uiStale?'alert':'check')}</span></button>`:'<div class="packet-placeholder">No task snapshot yet.</div>'}</div><footer>${!state.started?button('Record synthetic task','start','lane-action'):state.changed&&!state.reviewed?button('Try recompiling now','compile-early','lane-action'):state.reviewed&&!state.finished?button('Compile reviewed context','compile-final','lane-action'):button('Inspect exact packet','packet','lane-action')}</footer></article>
    <article class="stream-lane teal"><header><div class="lane-identity"><span class="agent-avatar">Q</span><div><h3>Quality & checks</h3><p>QA agent · independent stream</p></div></div><span class="branch">${icon('branch')}test/usage-contract</span><div class="lane-status"><span class="${state.changed?'status-changed':'status-current'}">${icon(state.changed?'alert':'check')}${state.changed?'Derived plan needs review':'Dependencies current'}</span><span>Plan v1</span></div></header><div class="lane-body">${state.changed?`<div class="drift-alert"><strong>${icon('alert')}Indirect dependency changed</strong><p>${state.reviewed?'The UI decision is now v2. This plan still refers to UI v1.':'This plan refers to UI v1, which was derived from the changed API contract.'}</p><button class="text-button" data-action="impact">Trace the chain ${icon('arrow')}</button></div>`:''}<div class="lane-section">Derived in this stream</div><button class="capsule-card" data-action="qa"><div class="card-top"><span class="kind kind-artifact">${icon('file')}Artifact</span><span>v1</span></div><h4>Verify the currency display</h4><p>Assert that 1,234 cents displays as $12.34. Test the conversion used by the dashboard.</p><div class="dependency-chip ${state.changed?'outdated':''}">${icon('link')}Based on UI display rule v1</div><div class="card-bottom">${icon('file')}Synthetic test plan<span>qa.currency</span></div></button><div class="chain-note"><span>API contract</span><b>→</b><span>UI rule</span><b>→</b><span>QA plan</span></div><p class="lane-aside">QA can be affected even without a direct connection to the API capsule.</p></div><footer><span class="stream-scope">Owns the verification plan</span><button class="text-button" data-action="qa">Inspect dependency ${icon('arrow')}</button></footer></article>`;
}
function inspectorHeading(kind,title,subtitle='') {return `<div class="inspector-heading"><span class="inspector-eyebrow">${kind}</span><h3>${title}</h3>${subtitle?`<p>${subtitle}</p>`:''}</div>`;}
function renderInspector() {
  let html='';const version=state.changed?2:1;
  if(state.panel==='contract') html=inspectorHeading(`Shared decision · v${version}`,contract[version].title,'One addressable contract, consumed by independent streams.')+`<div class="inspector-body"><pre class="source-code">${escape(contract[version].body)}</pre><p>${contract[version].explanation}</p><section><h4>${icon('file')}Evidence</h4><div class="evidence-card"><strong>Billing API specification</strong><span>repo://orbit/docs/billing-contract.md</span><small>Fictional source reference for this demo.</small></div></section><section><h4>Revision history</h4><div class="revision-row"><i></i><span>v${version}<small>${state.changed?'Added currency_exponent and renamed amount_cents.':'Initial cents-based response contract.'}</small></span><b>Current</b></div>${state.changed?'<div class="revision-row old"><i></i><span>v1<small>Original contract. Still present in the task’s first packet.</small></span></div>':''}</section>${state.changed?button('Inspect affected streams','impact','secondary full'):button('Record a task using v1','start','secondary full',state.started)}</div>`;
  else if(state.panel==='packet') {
    const packet=currentPacket();if(!packet){state.panel='contract';return renderInspector();}const drift=checkPacket(packet);const original=packet===state.packets[0];
    html=inspectorHeading('Immutable task snapshot',packet.id,original?'The original synthetic task used this exact context.':'A new snapshot never replaces the old one.')+`<div class="inspector-body"><div class="preflight ${drift.length?'blocked':'passed'}"><strong>${icon(drift.length?'alert':'check')}${drift.length?'Preflight: needs review':'Preflight: current'}</strong><p>${drift.length?drift.map(d=>d.title).join(' · '):'No changed dependencies in this synthetic snapshot.'}</p></div><div class="budget"><strong>${packet.tokens}<span> / ${packet.budget}</span></strong><span>estimated tokens</span></div><div class="budget-bar"><i style="width:${packet.tokens/packet.budget*100}%"></i></div><p class="tiny">Estimate covers the entire generated text; it is not a provider billing count.</p><section><h4>Exact revision manifest</h4>${packet.manifest.map(m=>`<div class="manifest-row"><span>${icon('file')}</span><div><strong>${m.title}</strong><small>${m.id} · ${m.mode}${m.dependency?` · based on API v${m.dependency}`:''}</small></div><b>v${m.version}</b></div>`).join('')}</section>${drift.length?`<section><h4>What changed</h4>${drift.map(d=>`<div class="change-detail"><strong>${d.title}</strong><p>${d.text}</p></div>`).join('')}</section>`:''}<details class="packet-text"><summary>Read compiled text</summary><pre>${escape(packet.text)}</pre></details><div class="inspector-actions">${button('Download packet','download','secondary')}${state.packets.length>1?button(original?'View latest':'View original',original?'latest':'original','secondary'):''}</div></div>`;
  } else if(state.panel==='impact') html=inspectorHeading('Dependency impact','A change travels further than a chat.','The dependency graph explains who needs to look again.')+`<div class="inspector-body"><div class="impact-source">${icon('branch')}<span>API contract<strong>${state.changed?'v1 → v2':'v1 · current'}</strong></span></div><div class="impact-path"><div><span class="path-dot coral"></span><strong>Usage dashboard</strong><b>${!state.changed||state.finished?'Current':'Needs review'}</b></div><p>Directly consumes API v1. Its display rule also derives from that exact revision.</p><div><span class="path-dot teal"></span><strong>Quality & checks</strong><b>${state.changed?'Needs review':'Current'}</b></div><p>Consumes the UI rule. The upstream API change makes this an indirect, transitive dependency.</p></div><section><h4>The original task is still traceable</h4><p>${state.started?'Its packet continues to reference contract v1. Historical context is never silently rewritten.':'Record the synthetic task to create an exact historical packet.'}</p>${state.started?button('Inspect original packet','original','secondary full'):''}</section><div class="review-callout"><strong>Fetching newer text is not revalidation.</strong><p>The display rule’s original assumption must be reviewed and published against the new source.</p>${!state.reviewed?button('Review the display rule','review','primary full'):button('Inspect reviewed packet',state.finished?'latest':'compile-final','primary full')}</div>${state.changed&&!state.reviewed?`<button class="text-button experiment-button" data-action="compile-early">What if I only recompile? ${icon('arrow')}</button>`:''}</div>`;
  else if(state.panel==='review' || state.panel==='display') html=inspectorHeading(`Derived decision · v${state.reviewed?2:1}`,'Review the assumption, then its reference.','A version link records what this claim was actually based on.')+`<div class="inspector-body"><div class="review-diff"><div class="before"><span>Before · based on API v1</span><code>amount_cents / 100</code><p>Assumes every currency has two decimal places.</p></div>${state.changed?'<div class="after"><span>Reviewed replacement · API v2</span><code>amount_minor / 10 ** currency_exponent</code><p>Uses the response’s explicit decimal exponent.</p></div>':''}</div><section><h4>Concrete consequence</h4><div class="example-value"><span>${state.changed?'1,234 minor units · BHD · exponent 3':'1,234 cents · USD'}</span><strong>${state.changed?'BHD 1.234':'$12.34'}</strong><small>${state.changed?'The original cents assumption is no longer valid.':'The original rule matches the v1 contract.'}</small></div></section>${!state.changed?'<p>This rule currently agrees with contract v1. Change the API contract to see the dependency break.</p>':state.reviewed?`<div class="preflight passed"><strong>${icon('check')}Reviewed claim v2 published</strong><p>The claim and its dependency now agree. Compile a packet to use this new revision.</p></div>${!state.finished?button('Compile a fresh packet','compile-final','primary full'):button('View current packet','latest','secondary full')}`:`<div class="review-consent"><p>In this synthetic scenario, you have inspected the old and new rules. Publishing records an explicit review of the updated contract.</p>${button('Publish reviewed claim v2','publish-reviewed','primary full')}</div><p class="tiny">A real workflow needs your agent or reviewer to assess the source and implementation. Loomplane does not perform that reasoning for you.</p>`}</div>`;
  else if(state.panel==='qa') html=inspectorHeading('Transitive dependency','QA owns its own review.','Independent streams keep independent responsibilities.')+`<div class="inspector-body"><div class="dependency-stack"><div><strong>QA plan v1</strong><span>derived from</span></div><div><strong>UI display rule v1</strong><span>derived from</span></div><div><strong>API contract v1</strong><span>${state.changed?'source is now v2':'current source'}</span></div></div><p>This test plan checks a two-decimal conversion. A change upstream can invalidate it even though QA never directly mounted the API contract.</p>${state.finished?'<div class="review-callout"><strong>The UI review does not sign off QA.</strong><p>The dashboard now has a current packet. QA still needs to review its own test plan and publish an updated dependency.</p></div>':''}<section><h4>Scope stays independent</h4><p>This demo stops after the dashboard is repaired. QA’s unresolved state is deliberate: one stream’s success should not silently clear another stream’s assumptions.</p></section>${button('Trace the impact','impact','secondary full')}</div>`;
  else if(state.panel==='model') html=inspectorHeading('Parallel context','Share a claim, not an entire conversation.','Every stream selects the context its own task needs.')+`<div class="inspector-body"><div class="model-principle"><span>01</span><div><strong>Independent task contexts</strong><p>API, UI, and QA can work in different tools and conversations.</p></div></div><div class="model-principle"><span>02</span><div><strong>Addressable shared knowledge</strong><p>A small capsule carries a decision, evidence, and immutable revision.</p></div></div><div class="model-principle"><span>03</span><div><strong>Explicit dependency checks</strong><p>A packet says exactly what was used. Later changes make its drift inspectable.</p></div></div><p class="inspector-endnote">This coordinates data between agents. It does not give a model an infinite context window or execute agents.</p>${button(state.started?'Return to the scenario':'Record a synthetic task',state.started?(state.changed?'impact':'packet'):'start','primary full')}</div>`;
  $('#inspector-label').textContent=state.panel==='packet'?'Packet inspector':state.panel==='impact'?'Impact inspector':'Context inspector';$('#inspector-content').innerHTML=html;
}
function render() {renderGuide();renderBoard();renderInspector();}
function act(action) {
  const inspectorHadFocus = document.activeElement?.closest('.inspector');
  if(action==='start'&&!state.started){state.started=true;createPacket();state.panel='packet';showToast('Synthetic task recorded against packet-demo-01. No agent was started.');}
  else if(action==='change'&&state.started&&!state.changed){state.changed=true;state.panel='contract';showToast('API v2 published. The original packet remains unchanged.');}
  else if(action==='impact'){state.impactSeen ||= state.changed;state.panel='impact';}
  else if(action==='review'){state.impactSeen ||= state.changed;state.panel='review';}
  else if(action==='compile-early'&&state.changed&&!state.reviewed){state.attempted=true;state.impactSeen=true;createPacket();state.panel='packet';showToast('Recompiled with API v2. Preflight still flags the derived display rule.');}
  else if(action==='publish-reviewed'&&state.changed&&!state.reviewed){state.reviewed=true;state.impactSeen=true;state.panel='review';showToast('Reviewed display rule v2 now references API contract v2.');}
  else if(action==='compile-final'&&state.reviewed){state.finished=true;createPacket();state.panel='packet';showToast('Dashboard preflight passed. QA still needs its own review.');}
  else if(action==='original'&&state.packets.length){state.selectedPacket=state.packets[0].id;state.panel='packet';}
  else if(action==='latest'||action==='packet'){state.selectedPacket=state.packets.at(-1)?.id;state.panel='packet';}
  else if(['contract','display','qa','model'].includes(action))state.panel=action;
  else if(action==='download'){const packet=currentPacket();if(packet){const url=URL.createObjectURL(new Blob([packet.text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`loomplane-${packet.id}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Synthetic packet downloaded.');}return;}
  render();
  if(action==='start') $('.scenario-guide').scrollIntoView({block:'start'});
  const revealInspector = window.matchMedia('(max-width: 1000px)').matches && ['review','impact','qa','model'].includes(action);
  if(revealInspector) $('.inspector').scrollIntoView({block:'start'});
  if(inspectorHadFocus || revealInspector) { const heading = $('#inspector-content h3'); heading.tabIndex = -1; heading.focus({preventScroll:true}); }
}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]');if(action&&!action.disabled)act(action.dataset.action);});
$('#reset').addEventListener('click',()=>{Object.assign(state,{started:false,changed:false,impactSeen:false,reviewed:false,finished:false,attempted:false,panel:'contract',packets:[],selectedPacket:null});render();showToast('Scenario reset. Everything starts at v1.');});
$('#show-model').addEventListener('click',()=>selectedPanel('model'));
$('#copy-install').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#install-commands').textContent);$('#copy-install').textContent='Copied';setTimeout(()=>$('#copy-install').textContent='Copy',1800);}catch{$('#copy-install').textContent='Select commands';const range=document.createRange();range.selectNodeContents($('#install-commands'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);}});
render();
